name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build and Deploy
        run: |
          # Create the public directory
          mkdir -p public
          
          # Copy all files from src to public
          cp -r src/* public/
          
          # Create .nojekyll file
          touch public/.nojekyll
          
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a new branch for GitHub Pages
          git checkout --orphan gh-pages
          
          # Remove all files except public directory
          git rm -rf .
          
          # Move public directory contents to root
          mv public/* .
          
          # Commit and push to gh-pages branch
          git add .
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to gh-pages branch
          git push -f origin gh-pages
